### PR TITLE
String like errors handling

### PR DESCRIPTION
**Pull request by randomhash**
Basically, inject original error if you can do this

### CODE REVIEW

**Comment by randomhash** [comment]
@willfarrel please merge at your convenience, e.originalError is breaking our production functionality, and it would be tough to resolve the issue on our side, would appreciate if we could keep it unbreaking for some some time

**Comment by randomhash** [comment]
Last commit is not required, but it's nice to have, as it was a bit hard navigate the code while there was inline chunky function

**Comment by randomhash** [comment]
Also it would be amazing if this change could be backported to middy 4

**Review by vladholubiev — APPROVED** [review]

**Comment by randomhash** [comment]
@willfarrell any chance to merge it today ?

**Comment by willfarrell** [comment]
Thanks for your patience, I was off on holiday. Spoke with @lmammino and we agree that this isn't good practice and don't think we should support it in core at this time.

**Comment by randomhash** [comment]
@willfarrell 
but your core is modifying the actual error message, it does not make any sense to add such hidden functionality without the possibility to disable it

**Pull request closed without merging**
