### PR TITLE
Fix middy import in definition file

### PR DESCRIPTION
**Pull request by Quelu**
Allow to use middy with Typescript imports

### CODE REVIEW

**Comment by ossareh** [comment]
@Quelu - can you give an example of the error you get from tsc without this change? 

From my local testing your change seems to be a noop.

**Comment by Quelu** [comment]
I'm having the error `'middy/index' has no default export` when I try to compile with tsc 2.8.3

**Comment by ossareh** [comment]
Hmm, odd. As I understand it (I'm not great at writing these type files for javascript projects) this is actually a default export: https://github.com/middyjs/middy/blob/master/index.d.ts#L41

In my own project this works just fine for me:

handler.ts
```
import middy from "middy";
```

package.json
```
	"dependencies": {
		... snip ...
		"middy": "^0.13.2"
	},
	"devDependencies": {
                 ... snip ...
		"ts-loader": "^4.3.0",
		"tslib": "^1.9.1",
		"typescript": "^2.8.3",
		"webpack": "^4.8.3",
		"webpack-cli": "^2.1.3"
	},
```

tsconfig.json
```
{
	"compilerOptions": {
		"allowSyntheticDefaultImports": true,
		"esModuleInterop": true,
		"experimentalDecorators": true,
		"importHelpers": true,
		"lib": [
			"es2018",
		],
		"moduleResolution": "node",
		"noEmitHelpers": true,
		"noEmitOnError": true,
		"noImplicitReturns": true,
		"target": "es6",
		"sourceMap": true,
		"strict": true,
	},
	"exclude": [
		"node_modules",
	]
}
```

Does your setup look somewhat similar?

**Comment by Quelu** [comment]
I added the allowSyntheticDefaultImports in my tsconfig and It works now !
Thank you for the help ;)

**Comment by ossareh** [comment]
Glad it was helpful @Quelu 👍

**Comment by astroanu** [comment]
I tried what the documentation says for typescript. but i still get that problem.

**Comment by ossareh** [comment]
@astroanu it would be helpful if you provided more information about your situation, for example your tsconfig.json would allow me to provide assistance.

**Pull request closed without merging**
