### PR TITLE
[secret-manager]: Add in support for secret rotation date

### PR DESCRIPTION
**Pull request by willfarrell**
@KillDozerX2 Can you give this a review and test? I don't personally use this service.

Adds in support for scheduled secret rotation.
Does not support manual secret rotation.

Closes: #1063

### CODE REVIEW

**Comment by KillDozerX2** [comment]
Need some time for this.

**Comment by willfarrell** [comment]
No worries, no rush

**Comment by willfarrell** [comment]
@KillDozerX2 Just wanted to follow up on this.

**Review by KillDozerX2 — APPROVED** [review]

**Review by KillDozerX2 — CHANGES_REQUESTED** [review]
Just one more request, sometimes the secrets are rotated by external process which results in the NextRotationDate being invalid. Can we provide an option for such a situation that would allow us to use `LastChangedDate` + `cacheExpiry`?

**Comment by willfarrell** [comment]
> Can we provide an option for such a situation that would allow us to use LastChangedDate + cacheExpiry
Is that not equivalent to setting the rotation schedule to equal `cacheExpiry`? If you're managing the rotation schedule yourself, I feel that is be out of scope for the core middy middlewares at this time.

**Comment by KillDozerX2** [comment]
> > Can we provide an option for such a situation that would allow us to use LastChangedDate + cacheExpiry
> 
> Is that not equivalent to setting the rotation schedule to equal `cacheExpiry`? If you're managing the rotation schedule yourself, I feel that is be out of scope for the core middy middlewares at this time.

Let's say we update a secret every 30 minutes ourself, we know that the secret has to be reset if cacheExpiry + LastUpdateTime is greater than 30 minutes. This is a real scenario and unfortunately we can't make everybody change the way they do things.

**Comment by willfarrell** [comment]
Apologies on the delay. I've updated to better support when `cacheExpiry` is set, allowing the secret to refresh before the rotation window. If you can do another review, I'll get this merged and released.

**Review by KillDozerX2 — APPROVED** [review]
This is Good! Thank you ❤️

**Pull request merged**
