### PR TITLE
Prevent the 'has no default export' error

### PR DESCRIPTION
**Pull request by ecentinela**

### CODE REVIEW

**Comment by lmammino** [comment]
Thanks, @ecentinela.
I'd love people with more experience than me in TypeScript to review this.

@ossareh  @joseSantacruz @vladgolubev @willfarrell @peterjcaulfield @nnyegaard @kevinrambaud @Jolg42

**Comment by ecentinela** [comment]
Sure @lmammino! Let me know if I can help!

**Comment by peterjcaulfield** [comment]
Sorry where are you getting this error @ecentinela ? `"esModuleInterop": true` in the tsconfig should solve this AFAIK.

**Comment by kevinrambaud** [comment]
Personally not sure how to handle that. I know that some people use the `module.exports.default = function middy() {}` pattern to avoid the error you mentionned.

In our case, middy library exports a function not an object. So I'd say our current declaration is ok and match with what typescript documentation recommends for module function (https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html)

The `"esModuleInterop": true` that @peterjcaulfield suggested is the way to go imo.

**Comment by ecentinela** [comment]
Cannot reproduce the error now, so, feel free to close this PR :)

**Comment by lmammino** [comment]
Thanks everyone here for the support :)

**Pull request closed without merging**
