### PR TITLE
New website using Docosaurus

### LINKED ISSUE #780: Re-build documentation website
- [x] choose docs generator
- [ ] build process (push to main)
- [ ] ensure all links don't return 404 #638
- [ ] clean up docs (v3 only)

Options:
- https://docusaurus.io/
- one used for https://getpino.io/#/ docsify
- https://www.freecodecamp.org/news/how-to-get-more-engagement-with-your-open-source-project/amp/

## Structure
- intro, what, install, getting started, why
  - release cycle
  - history
  - influence
- usage (core)
  - typescript 
  - inline middlewares
  - error handling
- performance (best practice)
- FAQ
- AWS events: (recommended middleware and order)
  - ...
- Middlewares:
  - ...
- Routers:
  - http-router
- Utilities (util)
  - getInternal
  - ...
- Plugin / Hooks
  - 
- write a middleware
- community middlewares
- contributing
- integreations
  -  examples using sls
  - works with pino
  - work with AppoloServer

### PR DESCRIPTION
**Pull request by lmammino**
This PR proposes a new redesign of the official Middy website (and related documentation) using [Docosaurus](https://docusaurus.io/) 

Closes #780

## Preview

A preview of the current build (based on this branch) is available at: https://new-middy-docs-demo.surge.sh/

### Major
- [x] Design Home page (put logo, remove default Docosaurus stuff, come up with a simple and concise list of what is middy and why it's useful)
- [x] Review structure of the website / documentation
- [x] Review all links and make sure the work and point to the right place (they should all be relative where possible)
- [ ] Complete TODO pages (or create dedicated issues for them)
- [x] Update/Create GitHub action to automatically build and deploy the website every time we merge to `main`
- [ ] Refactor Middy main readme (trim it down and link to the website for more info)
- [x] Enable search (algolia integration) - **Using Lunr right now, requested free open source access to Algolia.**
- [x] Make sure that the main documentation page points to `/docs` (currently this gives a 404)

### Minor/optional:
- [x] Update middy logo to work with `currentColor` and switch dynamically from light to dark mode
- [x] Update Middy lifecycle picture to be an SVG that works also in Dark mode (FOR NOW USING `filter: invert(1)` hack, which works well enough)
- [ ] Look into how to to do multi-version documentation (e.g. v2.x vs v3.x)
- [ ] Create a script to synchronise middleware READMEs with their documentation page on the website
- [ ] Similarly we could have a script to generate the main README based on content from the website/docs
- [x] Do proper Open Graph previews for the website (so that when the link is shared people get some decent preview of what middy is)
- [x] Custom 404 page

### CODE REVIEW

**Comment by willfarrell** [comment]
Favicon: `<svg viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><text x="0" y="14">🛵</text></svg>`

**Comment by willfarrell** [comment]
Just throwing the idea out there. What if `documentation` was in it's own repo?

**Comment by lmammino** [comment]
> Just throwing the idea out there. What if `documentation` was in it's own repo?

I prefer to keep it in the same repo because this way it would be easier to submit code changes together with equivalent documentation changes.

What do you think about the current structure of the documentation. Anything you would change?

**Comment by willfarrell** [comment]
> What do you think about the current structure of the documentation. Anything you would change?

I would change the order a bit, but I think it's good enough for now. I'm working on some AWS events.

Can code blocks be pulled from files? To allow easier linting and checks.

**Comment by lmammino** [comment]
> > What do you think about the current structure of the documentation. Anything you would change?
> 
> I would change the order a bit, but I think it's good enough for now. I'm working on some AWS events.
> 
> Can code blocks be pulled from files? To allow easier linting and checks.

I don't think it's possible with vanilla markdown but it might be possible to do that with MDX... It would be pretty cool if that works, but it needs some research

**Comment by lmammino** [comment]
I am attempting some copy for the home page (already committed). I haven't updated the preview but here's a screenshot:

Screenshot 2022-02-08 at 08 56 12

@willfarrell, let me know what do you think :)

Of course, i'll need to find some relevant images/icons...

**Comment by lmammino** [comment]
Added some iconz 👩🏽‍🎨 

Screenshot 2022-02-08 at 10 00 05

**Comment by lmammino** [comment]
Updated the [preview](https://new-middy-docs-demo.surge.sh/) with a possible design for the home page.


@willfarrell, I am struggling a little with the example part. Any idea on how to make the advantages of middy more obvious? Maybe some more realistic example with a couple of real official middleware?

**Comment by willfarrell** [comment]
This is for v3 only, but I think it highlights. See AWS Events for all real middleware examples. A lambda for an http event might be the most relatable?
```js
//shared-middlewares.js
import ....

export default middy()
  .use(...)
```
```js
// handler.js
import middlewares from './shared-middlewares.js'
import validatorMiddleware from '@middy/validator'

export const handler = middlewares
  .use(validatorMiddleware({...}))
  .handler((event, context, {signal}) => {
    // logic
})

```

PS that favicon hack works?? Sweet!

**Comment by lmammino** [comment]
Merging this to start migrating to the new website

**Pull request merged**
