### PR TITLE
Fix relative imports

### PR DESCRIPTION
**Pull request by sheepsteak**
Build on #315 by fixing all relative imports of `@middy/core` in 1.0.0-alpha.

- [x] Add `@middy/core` to `devDependencies` of packages
- [x] Change all relative imports

Closes #315.

### CODE REVIEW

**Comment by lmammino** [comment]
Hello @sheepsteak! First of all, thanks for this PR.
Anyway, I have a couple of questions.

I agree that we need to use absolute imports for typings (i guess otherwise they might not work as expected in certain scenarios.

I also agree about @middy/core being a devDependency, since we only use that within tests.

I am not so sold on why we want to change relative imports for tests. I have a feeling that keep using relative imports makes evolving the codebase easier by allowing us to keep everything tested and in sync before publishing a new release.

Am I missing something?

**Comment by sheepsteak** [comment]
> I am not so sold on why we want to change relative imports for tests. I have a feeling that keep using relative imports makes evolving the codebase easier by allowing us to keep everything tested and in sync before publishing a new release.

Sorry, I have no idea why I did this. I must have just seen `../../core` and thought it needed changing too. 😇

I've removed that commit and merged in latest 1.0.0-alpha.

**Comment by lmammino** [comment]
Thanks @sheepsteak.

I have another doubt (being a typescript noob!).

In the typings file we do:

```typescript
import middy from '@middy/core'
```

Will that work since we have `@middy/core` as a dev dependency or do we need to move that into `dependencies`?

**Comment by vladgolubev** [comment]
@lmammino it will work, since it is also in `peerDependencies`, so user won't get around w/o `@middy/core` installed

**Comment by lmammino** [comment]
Thanks @vladgolubev.

@sheepsteak I'll try to get this merged this by today/tomorrow! :)

**Pull request merged**
