### PR TITLE
return promise from instance if no callback is present

### PR DESCRIPTION
**Pull request by shroomist**
Solves #198 
Did not touch that much here, just wrapped `instance()` logic in `new Promise` and return it if no callback is present.

Signed-off-by: Andrej Novikov <jazzaiman@gmail.com>

### CODE REVIEW

**Comment by lmammino** [comment]
Thanks @shroomist, I'll version bump and get this one merged :)

**Comment by vikasgarghb** [comment]
Looks like this do not work when running your function with `sam local invoke`. There is this callback function which is being set:
```
function() {
      if (!finished) {
        toWrap.apply(null, arguments);
        finished = true;
      }
    }
```

So, the condition for resolving the promise is never reached and the function just hangs.

**Comment by vikasgarghb** [comment]
In order to get it working, I had to add this to my function: `context.callbackWaitsForEmptyEventLoop = false;`

**Comment by lmammino** [comment]
Helllo @vikasgarghb, which version of middy are you using? Would you like to open a dedicated issue and maybe a PR to help us to address this problem?

**Comment by vikasgarghb** [comment]
@lmammino I am on 1.0.0-beta. I will open a dedicated issue.

**Comment by vikasgarghb** [comment]
Basically the documentation needs to be updated that you need to use `doNotWaitForEmptyEventLoop` middleware to make async/await handler work with middy.

**Comment by vikasgarghb** [comment]
@lmammino https://github.com/middyjs/middy/issues/505

**Pull request merged**
