### PR TITLE
add sqs-json-body-parser to community middleware

### PR DESCRIPTION
**Pull request by Eomm**
I would like to add this first simple middleware to your list 👍

### CODE REVIEW

**Comment by willfarrell** [comment]
How is this different from the existing `sqs` middleware? Missing feature?

**Comment by Eomm** [comment]
Could you share a link?
I saw a sqs middleware per partial process elaboration 

In this case it just parse the body as a json using safe parser when needed

**Comment by Eomm** [comment]
Why closing?

**Comment by willfarrell** [comment]
Already committed to the readme :)

**Pull request closed without merging**
