### PR TITLE
feat: self-composing UseFN

### PR DESCRIPTION
**Pull request by vicary**
In respond to https://github.com/middyjs/middy/issues/769#issuecomment-1196279277, this is the first attempt to make the event object self- and auto- composing through the chain of `.use()`.

Intended usage:
```ts
import type middy from "@middy/core";
import type { Context } from "aws-lambda";

const middyFoo = (): middy.MiddlewareObj<{ evtFoo: string }, any, Error, Context & { ctxFoo: string }> => ({
  before: ({ context, event }) => {
    context.ctxFoo = "foo";
    event.evtFoo = "foo";
  },
});

const middyBar = (): middy.MiddlewareObj<{ evtBar: string }, any, Error, Context & { ctxBar: string }> => ({
  before: ({ context, event }) => {
    context.ctxBar = "bar";
    event.evtBar = "bar";
  },
});


export const handler = middy()
  .use(middyFoo())
  .use(middyBar())
  .before(({ context: { ctxFoo, ctxBar }, event: { evtFoo, evtBar } }) => {
    // context and event inherits new properties from the .use() above
  })
  .handler(({ evtFoo, evtBar }, { ctxFoo, ctxBar }) => {
    // context and event inherits new properties from the .use() above
  });
```

### CODE REVIEW

**Comment by vicary** [comment]
@willfarrell Should it be 3.0 or 4.0?

Also some old plugins add something to lambda context, while others add to events. I am kinda leaning towards extending the event object, so I intentionally left `TContext` untouched. Do you have a preference or encourage either side?

**Comment by willfarrell** [comment]
v4 is on hold till we know what AWS is going to do for their next runtime update (v18). That could be as early as Sept, or a year from now. I'm open to minor changes for v3 for now. There can also be a separate PR for v4, to allow others to comment.

Changes to the event are the most common use in middlewares, however non-external inputs (ie secrets, db connections, etc) should live in the context.

I personally don't use TS, so it's up to the community to decide what is best for Middy. This PR looks safe fro v3.

**Comment by vicary** [comment]
My team is currently adding everything to event, including `typeorm` and `fetch`, to make handlers testable.

But I want this PR to be generally align with your advertised usage, I'll update this PR again to have `TContext` also inherits through the chain of `.use()`.

**Comment by vicary** [comment]
@willfarrell It's ready now.

Tried avoiding the necessity of `Context & ...` in usage, but that breaks the `extends LambdaContext` check. I chose to retain a more guaranteed typing.

Usage example in the description is updated to reflect the change.

**Comment by vicary** [comment]
@willfarrell It's ready now.

Tried avoiding the necessity of `Context & ...` in usage, but that breaks the `extends LambdaContext` check. I chose to retain a more guaranteed typing.

Usage example in the description is updated to reflect the change.

**Comment by vicary** [comment]
We may update the types in all packages, shall I do that here or in a new PR?

For example, `@middy/cloudwatch-metrics` with typings:

```ts
export const handler = middy()
  .use(cloudwatchMetrics())
  .handler(({}, { metrics }) => {
    // The `metrics` property and its methods will be discoverable by IDEs
  });
```

**Comment by willfarrell** [comment]
Within this PR is fine.

**Comment by vicary** [comment]
TypeScript has no way to perform string matching without introducing unused vars, I have to skip these errors.

https://github.com/middyjs/middy/blob/09937572e16d6fa5802e642439e972828a3e49aa/packages/ssm/index.d.ts#L10-L15

**Comment by vicary** [comment]
Took another look at SSM and noticed a mistype, fixed it.

**Sidenote**

`ts-standard` (`npm run test:lint:ci`) is not suitable for typescript linting because there are broken rules, for example https://github.com/typescript-eslint/typescript-eslint/issues/1824.

I think we should use `eslint` directly so we can opt-in and out of particular rules, along with `eslint-plugin-prettier` so contributors can easily fix trivial format misalignments.

That's for another PR though, I'll stick with the broken indentations here to stay green.

**Review by willfarrell — APPROVED** [review]

**Comment by willfarrell** [comment]
Looks good to me. I'm going to leave it open in case other would like to comment. I can merge and release next week. Thanks for all of the hard work putting this together.

**Pull request merged**
