### PR TITLE
fix: typescript support getOrigin

### PR DESCRIPTION
**Pull request by garbray**
Add typescript support to enable override getOrigin functions

[#776 ](https://github.com/middyjs/middy/issues/776)

---------------------------
**Node.js Versions: 16.13.1

### CODE REVIEW

**Comment by willfarrell** [comment]
Thanks for the PR. Can you reapply your changes to the `release/3.x` branch please. I hope to have an alpha out this weekend. I can then cherry pick bug fixes down to `2.x`

**Comment by garbray** [comment]
sure, let me take a look on that branch and see what needs to be done right there 👍

**Comment by garbray** [comment]
looks like it was already tackle here [#774 (https://github.com/middyjs/middy/commit/4faa941a244d2e9aa0a4be7cb6859826cb0ac98f#diff-a8b6539fe48ed5f94844d198643cac1b3842ee53921ea617e312f33cd92b3580) let me know if anything else I can help with 👍

**Comment by willfarrell** [comment]
I had a feeling it looked familiar :).

**Pull request closed without merging**
