### PR TITLE
FucntionShield: add warning and bump dep version

### PR DESCRIPTION
**Pull request by willfarrell**
Addresses #460

### CODE REVIEW

**Comment by willfarrell** [comment]
There are on ~250 download/week (https://www.npmjs.com/package/@middy/function-shield)

It might be easier to just keep it in till the number drops down to near zero then remove it from the future versions.

**Comment by lmammino** [comment]
Yeah, I was thinking to keep it in the same npm package, but just move the repo outside the main one to start cleaning up. It shouldn't be too much work, I'll try to do it during the day.

This way we can avoid publishing new releases of this when there are new releases of middy and vice-versa.

What do you think?

**Comment by willfarrell** [comment]
I feel putting it in its own repo would mean we have to maintain it longer by having to keep the repo in the org.

**Comment by lmammino** [comment]
Fair enough. I will get this merged soon :)

**Pull request merged**
