### PR TITLE
Support streamifyResponse

### LINKED ISSUE #1038: Support Stream Repsonse
https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/

Examples
https://github.com/aws-samples/serverless-patterns/blob/main/lambda-streaming-large-sam/src/index.js
https://github.com/aws-samples/serverless-patterns/blob/main/lambda-streaming-ttfb-pipeline-sam/src/index.mjs

### PR DESCRIPTION
**Pull request by willfarrell**
Closes #1038

- [x] middy supports streamifyResponse with ReadableStream body
- [x] middy supports streamifyResponse without ReadableStream body (needed?)
- [x] Add new docs page
- [x] http-content-encoding support ReadableStream body
- [x] Update http-content-encoding docs
- [x] real lambda testing

## Test
Using Function URL, arm, nodejs18.x, esm

```js
import middy from '@middy/core'
export const handler = middy({ streamifyResponse: true })
  .handler(() => {
    return {
      statusCode: ***,
      headers: {
        'Content-Type': 'text/plain',
        'X-Custom-Header': 'Example-Custom-Header'
      },
      body: ***
    }
  })
```

### CODE REVIEW

**Comment by willfarrell** [comment]
`@middy/core` takes care of all that complexity for you. You just need to return a ReadableStream.

`@datastream/core` is my got for managin streams. Take a look at: https://github.com/willfarrell/datastream/blob/main/packages/core/index.node.js#L141 for an example on how to create them.

**Comment by abarone-btf** [comment]
sorry if the question is too noob :(, but how do I "write" to the stream constantly before returning it?. I need to write in various part of the code, not just at the end when returning.

// write to stream
// async - wait "long" call
// write again to the stream
// async - wait "long" call
// write again to the stream 
// return

@willfarrell

**Comment by willfarrell** [comment]
All good bro, try something like this:

```javascript
function* iterator() {
  for (var i = 0; i <= 100; i++) {
      await new Promise(r => setTimeout(r, 20));
      yield `Hello ${i} \n`
    }		
}

return {
  statusCode: 200,
  body: Readable.from(iterator(), streamOptions);
}
```

**Comment by willfarrell** [comment]
Glad I could help. 😊

**Pull request merged**
